app:
  bot:
    token: ''
    shards:
      total: 2
  images:
    ip: 127.0.0.1
    port: 8080
  prometheus:
    host: ''
  legacy:
    ip: '127.0.0.1'
    port: 6379
    password: 'password'
spring:
  datasource:
    url: jdbc:mariadb://host:3306/database?UseUnicode=true&amp;characterEncoding=utf8
    username: username
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 480000
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
  data:
    redis:
      port: 6379
      password: password
      host: 127.0.0.1
